development:
  adapter: postgresql
  database: ror_prefeitura_oficio
  pool: 5
  timeout: 8000

test:
  adapter: postgresql
  database: ror_prefeitura_oficio
  pool: 5
  timeout: 8000

production:
  adapter: postgresql
  database: ror_prefeitura_oficio
  pool: 5
  timeout: 8000
